spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug

server:
  servlet:
    encoding:
      force: true

event:
  schedule:
    cron: 0 0 0/1 * * *